name: openbrain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  - pip:
    - fastapi
    - uvicorn
    - transformers
    - auto-gptq
    - jinja2
    - httpx
    - pydantic
    - torch
    - accelerate